version: '3.1'

services:
    db:
        image: mysql:8.0
        container_name: task_mysql
        environment:
        - MYSQL_USER=Andrey
        - MYSQL_PASSWORD=123
        - MYSQL_ROOT_PASSWORD=root
        ports:
        - 3306:3306
        volumes:
        - ./mysql:/var/lib/mysql/


    graph:
        image: neo4j:3.5.4
        container_name: task_neo4j
        ports:
        - 7474:7474
        - 7687:7687
        extra_hosts:
        - "neo.loc:10.0.0.1"
        volumes:
        - ./neoj4/data:/data/

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
        - 2181:2181

    kafka:
        image: wurstmeister/kafka:0.10.1.1
        ports:
        - 9092:9092
        depends_on:
        - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "user:1:1,task:1:1"